# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets


def _translate(context, text, disambig=None):
    return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblFileList = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblFileList.setAcceptDrops(True)
        self.tblFileList.setObjectName("tblFileList")
        self.tblFileList.setColumnCount(0)
        self.tblFileList.setRowCount(0)
        self.tblFileList.horizontalHeader().setStretchLastSection(True)
        self.tblFileList.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.tblFileList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblInputEncoding = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInputEncoding.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.lblInputEncoding.setObjectName("lblInputEncoding")
        self.horizontalLayout.addWidget(self.lblInputEncoding)
        self.cboInputEnc = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cboInputEnc.setObjectName("cboInputEnc")
        self.horizontalLayout.addWidget(self.cboInputEnc)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblOutputEncoding = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutputEncoding.setObjectName("lblOutputEncoding")
        self.horizontalLayout.addWidget(self.lblOutputEncoding)
        self.cboOutputEnc = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cboOutputEnc.setObjectName("cboOutputEnc")
        self.horizontalLayout.addWidget(self.cboOutputEnc)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnConvert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConvert.setEnabled(False)
        self.btnConvert.setObjectName("btnConvert")
        self.horizontalLayout.addWidget(self.btnConvert)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAddFiles = QtGui.QAction(parent=MainWindow)
        self.actionAddFiles.setObjectName("actionAddFiles")
        self.actionAddFolder = QtGui.QAction(parent=MainWindow)
        self.actionAddFolder.setObjectName("actionAddFolder")
        self.actionClearList = QtGui.QAction(parent=MainWindow)
        self.actionClearList.setEnabled(False)
        self.actionClearList.setObjectName("actionClearList")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionMaximumFileSize = QtGui.QAction(parent=MainWindow)
        self.actionMaximumFileSize.setObjectName("actionMaximumFileSize")
        self.actionRemoveFiles = QtGui.QAction(parent=MainWindow)
        self.actionRemoveFiles.setEnabled(False)
        self.actionRemoveFiles.setObjectName("actionRemoveFiles")
        self.menuFile.addAction(self.actionAddFiles)
        self.menuFile.addAction(self.actionAddFolder)
        self.menuFile.addAction(self.actionRemoveFiles)
        self.menuFile.addAction(self.actionClearList)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionMaximumFileSize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionAddFiles)
        self.toolBar.addAction(self.actionAddFolder)
        self.toolBar.addAction(self.actionRemoveFiles)
        self.toolBar.addAction(self.actionClearList)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "bwEnc"))
        self.lblInputEncoding.setText(_translate("MainWindow", "Input encoding:"))
        self.lblOutputEncoding.setText(_translate("MainWindow", "Output encoding:"))
        self.btnConvert.setText(_translate("MainWindow", "Convert"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAddFiles.setText(_translate("MainWindow", "Add files..."))
        self.actionAddFolder.setText(_translate("MainWindow", "Add folder..."))
        self.actionAddFolder.setToolTip(_translate("MainWindow", "Add folder"))
        self.actionClearList.setText(_translate("MainWindow", "Clear list"))
        self.actionClearList.setToolTip(_translate("MainWindow", "Clear list"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionMaximumFileSize.setText(_translate("MainWindow", "Maximum file size..."))
        self.actionRemoveFiles.setText(_translate("MainWindow", "Remove files"))
        self.actionRemoveFiles.setToolTip(_translate("MainWindow", "Remove files"))
